name: Custom V2RayNG Build

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build Libv2ray Core AAR with Go
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init
        
        mkdir -p V2rayNG/app/libs
        
        if [ -d "AndroidLibXrayLite" ]; then
          cd AndroidLibXrayLite
          gomobile bind -v -target=android -androidapi 21 -ldflags="-s -w" -o ../V2rayNG/app/libs/libv2ray.aar .
          cd ..
        fi

    - name: Build Debug APK
      run: |
        chmod +x V2rayNG/gradlew
        cd V2rayNG
        ./gradlew assembleFdroidDebug --no-daemon

    - name: Upload Custom APK
      uses: actions/upload-artifact@v4
      with:
        name: My-Custom-V2RayNG
        path: V2rayNG/app/build/outputs/apk/**/*.apk
